[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = [
    'python manage.py migrate --noinput'
]

[start]
cmd = 'gunicorn basicfit_project.wsgi:application --bind 0.0.0.0:$PORT'

[variables]
PYTHONPATH = '/app'
DJANGO_SETTINGS_MODULE = 'basicfit_project.settings.railway'