# Generated by Django 4.2.7 on 2025-08-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilutilisateur',
            table='bf_profils_utilisateurs',
        ),
        migrations.AlterModelTable(
            name='user',
            table='bf_utilisateurs',
        ),
    ]
