# Generated by Django 4.2.7 on 2025-07-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriexercice',
            name='repos_reel',
        ),
        migrations.AddField(
            model_name='exerciceseance',
            name='duree_prevue',
            field=models.PositiveIntegerField(blank=True, help_text='Durée prévue en secondes (pour exercices de durée)', null=True, verbose_name='Durée prévue (s)'),
        ),
        migrations.AddField(
            model_name='exerciceseance',
            name='duree_realisee',
            field=models.PositiveIntegerField(blank=True, help_text='Durée réalisée en secondes (pour exercices de durée)', null=True, verbose_name='Durée réalisée (s)'),
        ),
        migrations.AddField(
            model_name='exerciceseance',
            name='repos_reel',
            field=models.PositiveIntegerField(blank=True, help_text='Repos réel en secondes', null=True, verbose_name='Repos réel (s)'),
        ),
        migrations.AddField(
            model_name='seriexercice',
            name='duree_prevue',
            field=models.PositiveIntegerField(blank=True, help_text='Durée prévue en secondes (pour exercices de durée)', null=True, verbose_name='Durée prévue (s)'),
        ),
        migrations.AddField(
            model_name='seriexercice',
            name='duree_realisee',
            field=models.PositiveIntegerField(blank=True, help_text='Durée réalisée en secondes (pour exercices de durée)', null=True, verbose_name='Durée réalisée (s)'),
        ),
    ]
