# Generated by Django 4.2.7 on 2025-08-07 19:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_remove_seriexercice_repos_reel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeanceSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('machine_nom', models.CharField(max_length=200, verbose_name='Nom de la machine')),
                ('date_seance', models.DateField(verbose_name='Date de la séance')),
                ('type_exercice', models.CharField(choices=[('CARDIO', 'Cardio'), ('MUSCULATION', 'Musculation'), ('FORCE', 'Force'), ('ENDURANCE', 'Endurance'), ('GAINAGE', 'Gainage'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name="Type d'exercice")),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée en minutes')),
                ('note_ressenti', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Note de ressenti (1-10)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_simples', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Séance Simple',
                'verbose_name_plural': 'Séances Simples',
                'ordering': ['-date_seance', 'machine_nom'],
                'indexes': [models.Index(fields=['utilisateur', 'date_seance'], name='workouts_se_utilisa_9f634f_idx'), models.Index(fields=['date_seance'], name='workouts_se_date_se_90bd90_idx')],
            },
        ),
    ]
