# Generated by Django 4.2.7 on 2025-08-23 07:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0013_machine_image_gif'),
        ('core', '0001_initial'),
        ('workouts', '0003_seancesimple'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la séance planifiée')),
                ('date_prevue', models.DateTimeField(verbose_name='Date prévue')),
                ('duree_prevue', models.PositiveIntegerField(default=60, help_text='Durée prévue en minutes', verbose_name='Durée prévue (min)')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('REPORTEE', 'Reportée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='PLANIFIEE', max_length=15, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('mode_entrainement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modeentrainement', verbose_name="Mode d'entraînement")),
            ],
            options={
                'verbose_name': 'Séance planifiée',
                'verbose_name_plural': 'Séances planifiées',
                'ordering': ['-date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='SeanceEffectuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la séance')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('volume_total', models.FloatField(default=0.0, help_text='Volume total (poids × reps × séries) de toute la séance', verbose_name='Volume total')),
                ('tonnage_total', models.FloatField(default=0.0, help_text='Tonnage total soulevé en kg', verbose_name='Tonnage total (kg)')),
                ('nombre_exercices', models.PositiveIntegerField(default=0, verbose_name="Nombre d'exercices")),
                ('nombre_series_totales', models.PositiveIntegerField(default=0, verbose_name='Nombre de séries totales')),
                ('note_ressenti', models.PositiveIntegerField(blank=True, help_text='Note de ressenti de 1 à 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Note de ressenti')),
                ('note_difficulte', models.PositiveIntegerField(blank=True, help_text='Note de difficulté de 1 à 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Note de difficulté')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Séance effectuée',
                'verbose_name_plural': 'Séances effectuées',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ExercicePlanifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('ordre_prevu', models.PositiveIntegerField(default=1, verbose_name='Ordre prévu')),
                ('series_prevues', models.PositiveIntegerField(default=3, verbose_name='Séries prévues')),
                ('repetitions_prevues', models.PositiveIntegerField(default=10, verbose_name='Répétitions prévues')),
                ('poids_prevu', models.FloatField(verbose_name='Poids prévu (kg)')),
                ('repos_prevu', models.PositiveIntegerField(default=90, help_text='Repos prévu entre séries en secondes', verbose_name='Repos prévu (s)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('calendrier_seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_planifies', to='workouts.calendrierseance', verbose_name='Séance planifiée')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Exercice planifié',
                'verbose_name_plural': 'Exercices planifiés',
                'ordering': ['calendrier_seance', 'ordre_prevu'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceEffectue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom_exercice', models.CharField(max_length=200, verbose_name="Nom de l'exercice")),
                ('ordre_dans_seance', models.PositiveIntegerField(default=1, verbose_name='Ordre dans la séance')),
                ('series_realisees', models.PositiveIntegerField(verbose_name='Séries réalisées')),
                ('repetitions_totales', models.PositiveIntegerField(verbose_name='Répétitions totales')),
                ('poids_moyen', models.FloatField(verbose_name='Poids moyen utilisé (kg)')),
                ('repos_moyen', models.PositiveIntegerField(default=90, help_text='Repos moyen entre séries en secondes', verbose_name='Repos moyen (s)')),
                ('volume_exercice', models.FloatField(default=0.0, help_text='Volume total de cet exercice', verbose_name='Volume exercice')),
                ('tonnage_exercice', models.FloatField(default=0.0, help_text='Tonnage de cet exercice', verbose_name='Tonnage exercice')),
                ('taux_reussite', models.FloatField(default=100.0, help_text='Pourcentage de réussite des séries prévues', verbose_name='Taux de réussite (%)')),
                ('charge_max_estimee', models.FloatField(blank=True, help_text='1RM estimé avec formule de Brzycki', null=True, verbose_name='1RM estimé (kg)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Machine')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='workouts.seanceeffectuee', verbose_name='Séance')),
            ],
            options={
                'verbose_name': 'Exercice effectué',
                'verbose_name_plural': 'Exercices effectués',
                'ordering': ['seance', 'ordre_dans_seance'],
            },
        ),
        migrations.AddField(
            model_name='calendrierseance',
            name='seance_effectuee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planification_origine', to='workouts.seanceeffectuee', verbose_name='Séance effectuée'),
        ),
        migrations.AddField(
            model_name='calendrierseance',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier_seances', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='SerieEffectuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero_serie', models.PositiveIntegerField(verbose_name='Numéro de série')),
                ('repetitions_realisees', models.PositiveIntegerField(verbose_name='Répétitions réalisées')),
                ('repetitions_prevues', models.PositiveIntegerField(verbose_name='Répétitions prévues')),
                ('poids_utilise', models.FloatField(verbose_name='Poids utilisé (kg)')),
                ('repos_apres_serie', models.PositiveIntegerField(blank=True, help_text='Repos après cette série en secondes', null=True, verbose_name='Repos après série (s)')),
                ('duree_serie', models.PositiveIntegerField(blank=True, help_text='Durée de la série en secondes', null=True, verbose_name='Durée série (s)')),
                ('note_effort', models.PositiveIntegerField(blank=True, help_text="Note d'effort perçu (RPE)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name="Note d'effort")),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='workouts.exerciceeffectue', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Série effectuée',
                'verbose_name_plural': 'Séries effectuées',
                'ordering': ['exercice', 'numero_serie'],
                'unique_together': {('exercice', 'numero_serie')},
            },
        ),
        migrations.AddIndex(
            model_name='seanceeffectuee',
            index=models.Index(fields=['utilisateur', 'date_debut'], name='workouts_se_utilisa_3e3486_idx'),
        ),
        migrations.AddIndex(
            model_name='seanceeffectuee',
            index=models.Index(fields=['date_debut'], name='workouts_se_date_de_069c91_idx'),
        ),
        migrations.AddIndex(
            model_name='calendrierseance',
            index=models.Index(fields=['utilisateur', 'date_prevue'], name='workouts_ca_utilisa_254ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='calendrierseance',
            index=models.Index(fields=['statut'], name='workouts_ca_statut_388601_idx'),
        ),
    ]
