# Generated by Django 4.2.7 on 2025-08-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_calendrierseance_seanceeffectuee_exerciceplanifie_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seanceentrainement',
            new_name='bf_seances__utilisa_7fe1cc_idx',
            old_name='workouts_se_utilisa_ea2277_idx',
        ),
        migrations.RenameIndex(
            model_name='seanceentrainement',
            new_name='bf_seances__statut_1f2bfb_idx',
            old_name='workouts_se_statut_cec228_idx',
        ),
        migrations.AlterModelTable(
            name='exerciceseance',
            table='bf_exercices_realises',
        ),
        migrations.AlterModelTable(
            name='progressionmachine',
            table='bf_progression_utilisateurs',
        ),
        migrations.AlterModelTable(
            name='seanceentrainement',
            table='bf_seances_entrainement',
        ),
        migrations.AlterModelTable(
            name='seriexercice',
            table='bf_series_exercices',
        ),
    ]
