# Generated by Django 4.2.7 on 2025-08-26 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0014_rename_tables_meaningful_names'),
        ('workouts', '0005_rename_tables_meaningful_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierEntrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_entrainement', models.DateField(verbose_name="Date d'entraînement")),
                ('nom_seance', models.CharField(max_length=200, verbose_name='Nom de la séance')),
                ('mode_entrainement', models.CharField(help_text='Ex: Prise de masse, Sèche, Force, etc.', max_length=100, verbose_name="Mode d'entraînement")),
                ('duree_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée en minutes')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('nombre_exercices', models.PositiveIntegerField(default=0, verbose_name="Nombre d'exercices")),
                ('volume_total', models.FloatField(default=0.0, help_text='Volume total (poids × reps) de la séance', verbose_name='Volume total')),
                ('source_donnees', models.CharField(choices=[('CSV_IMPORT', 'Import CSV'), ('PLANIFICATION', 'Planification'), ('SAISIE_MANUELLE', 'Saisie manuelle')], default='CSV_IMPORT', max_length=50, verbose_name='Source des données')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='TERMINE', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier_entrainements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Entrainement calendrier',
                'verbose_name_plural': 'Entrainements calendrier',
                'db_table': 'bf_calendrier_entrainements',
                'ordering': ['-date_entrainement'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom_exercice', models.CharField(max_length=200, verbose_name="Nom de l'exercice")),
                ('ordre_dans_seance', models.PositiveIntegerField(default=1, verbose_name='Ordre dans la séance')),
                ('series_effectuees', models.PositiveIntegerField(default=1, verbose_name='Nombre de séries')),
                ('repetitions_totales', models.PositiveIntegerField(default=10, verbose_name='Répétitions totales')),
                ('poids_utilise', models.FloatField(default=0.0, verbose_name='Poids utilisé (kg)')),
                ('volume_exercice', models.FloatField(default=0.0, help_text='Poids × répétitions', verbose_name='Volume exercice')),
                ('calendrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='workouts.calendrierentrainement', verbose_name='Entrainement calendrier')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machine', verbose_name='Machine associée')),
            ],
            options={
                'verbose_name': 'Exercice calendrier',
                'verbose_name_plural': 'Exercices calendrier',
                'db_table': 'bf_exercices_calendrier',
                'ordering': ['calendrier', 'ordre_dans_seance'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceManuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom_exercice', models.CharField(max_length=200, verbose_name="Nom de l'exercice")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('series_par_defaut', models.PositiveIntegerField(default=3, verbose_name='Séries par défaut')),
                ('repetitions_par_defaut', models.PositiveIntegerField(default=10, verbose_name='Répétitions par défaut')),
                ('poids_par_defaut', models.FloatField(default=0.0, verbose_name='Poids par défaut (kg)')),
                ('repos_par_defaut', models.PositiveIntegerField(default=90, help_text='Repos par défaut en secondes', verbose_name='Repos par défaut (s)')),
                ('est_favori', models.BooleanField(default=False, verbose_name='Exercice favori')),
                ('nombre_utilisations', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('groupe_musculaire_cible', models.CharField(blank=True, max_length=100, verbose_name='Groupe musculaire ciblé')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machine', verbose_name='Machine associée')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_manuels', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Exercice manuel',
                'verbose_name_plural': 'Exercices manuels',
                'db_table': 'bf_exercices_manuels',
                'ordering': ['-est_favori', '-nombre_utilisations', 'nom_exercice'],
                'indexes': [models.Index(fields=['utilisateur', 'est_favori'], name='bf_exercice_utilisa_206d7b_idx'), models.Index(fields=['machine'], name='bf_exercice_machine_417d20_idx')],
                'unique_together': {('utilisateur', 'nom_exercice')},
            },
        ),
        migrations.AddIndex(
            model_name='calendrierentrainement',
            index=models.Index(fields=['utilisateur', 'date_entrainement'], name='bf_calendri_utilisa_79f1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='calendrierentrainement',
            index=models.Index(fields=['source_donnees'], name='bf_calendri_source__f0ee04_idx'),
        ),
        migrations.AddIndex(
            model_name='calendrierentrainement',
            index=models.Index(fields=['statut'], name='bf_calendri_statut_4b2cfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendrierentrainement',
            unique_together={('utilisateur', 'date_entrainement', 'nom_seance')},
        ),
    ]
