# Generated by Django 4.2.7 on 2025-08-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0014_rename_tables_meaningful_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0006_create_calendar_and_manual_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceEffectueUnifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('source', models.CharField(choices=[('CSV_IMPORT', 'Import CSV calendrier'), ('MANUEL_TEMPS_REEL', 'Entraînement manuel temps réel'), ('EXERCICE_INDIVIDUEL', 'Exercice individuel'), ('IMPORT_EXTERNE', 'Import externe (autre app)')], help_text="Origine de l'exercice", max_length=30)),
                ('date_exercice', models.DateTimeField(help_text="Date et heure de réalisation de l'exercice")),
                ('nom_seance', models.CharField(blank=True, help_text='Nom de la séance si applicable', max_length=200, null=True)),
                ('duree_seance_minutes', models.PositiveIntegerField(blank=True, help_text='Durée totale de la séance en minutes', null=True)),
                ('nom_exercice', models.CharField(help_text="Nom de l'exercice effectué", max_length=200)),
                ('series_effectuees', models.PositiveIntegerField(help_text='Nombre de séries réalisées')),
                ('repetitions_totales', models.PositiveIntegerField(help_text='Total des répétitions sur toutes les séries')),
                ('poids_utilise', models.DecimalField(decimal_places=2, help_text='Poids utilisé (kg)', max_digits=6)),
                ('volume_total', models.DecimalField(decimal_places=2, editable=False, help_text='Volume total (poids × répétitions)', max_digits=10)),
                ('ligne_csv_originale', models.TextField(blank=True, help_text='Ligne CSV originale (pour debug)', null=True)),
                ('taux_reussite', models.DecimalField(decimal_places=2, default=100.0, help_text="Pourcentage de réussite de l'exercice", max_digits=5)),
                ('temps_repos_seconde', models.PositiveIntegerField(blank=True, help_text="Temps de repos après l'exercice (secondes)", null=True)),
                ('commentaire_utilisateur', models.TextField(blank=True, help_text="Commentaire de l'utilisateur sur l'exercice", null=True)),
                ('machine', models.ForeignKey(blank=True, help_text='Machine utilisée (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_effectues_unifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercice effectué',
                'verbose_name_plural': 'Exercices effectués',
                'db_table': 'bf_exercices_effectues',
                'ordering': ['-date_exercice', 'nom_exercice'],
                'indexes': [models.Index(fields=['utilisateur', 'date_exercice'], name='bf_exercice_utilisa_2c30ea_idx'), models.Index(fields=['utilisateur', 'machine'], name='bf_exercice_utilisa_adb55e_idx'), models.Index(fields=['utilisateur', 'nom_exercice'], name='bf_exercice_utilisa_45a95e_idx'), models.Index(fields=['source', 'date_exercice'], name='bf_exercice_source_2571bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendrierEntrainementSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_entrainement', models.DateField()),
                ('nom_seance', models.CharField(max_length=200)),
                ('duree_totale_minutes', models.PositiveIntegerField(help_text='Durée totale de la séance')),
                ('nombre_exercices', models.PositiveIntegerField(default=0, help_text="Nombre d'exercices dans cette séance")),
                ('volume_total_seance', models.DecimalField(decimal_places=2, default=0.0, help_text='Volume total de la séance', max_digits=10)),
                ('source_donnees', models.CharField(choices=[('CSV_IMPORT', 'Import CSV'), ('MANUEL', 'Séance manuelle'), ('PLANIFIE', 'Séance planifiée réalisée')], default='MANUEL', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier_entrainements_simples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Séance d'entraînement",
                'verbose_name_plural': "Séances d'entraînement",
                'db_table': 'bf_calendrier_simple',
                'ordering': ['-date_entrainement'],
                'unique_together': {('utilisateur', 'date_entrainement', 'nom_seance')},
            },
        ),
    ]
