# Generated by Django 4.2.7 on 2025-08-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_create_unified_architecture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeanceSimple',
        ),
    ]
