# Generated by Django 4.2.7 on 2025-07-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_machine_categories_many_to_many'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='machinecategorie',
            name='machines_mac_machine_123456_idx',
        ),
        migrations.RemoveIndex(
            model_name='machinecategorie',
            name='machines_mac_categor_789012_idx',
        ),
    ]
