# Generated by Django 4.2.7 on 2025-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_add_seated_triceps_press_and_dip_assist'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='type_exercice',
            field=models.CharField(choices=[('REPETITIONS', 'Répétitions'), ('DUREE', 'Durée')], default='REPETITIONS', help_text="Type d'exercice : répétitions ou durée", max_length=15, verbose_name="Type d'exercice"),
        ),
    ]
