# Generated by Django 4.2.7 on 2025-07-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_add_type_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image_gif',
            field=models.ImageField(blank=True, null=True, upload_to='machines/gifs/', verbose_name='GIF démonstratif'),
        ),
    ]
