# Generated by Django 4.2.7 on 2025-01-27 15:30

from django.db import migrations, models


def update_cardio_machines_to_duration(apps, schema_editor):
    """Met à jour les machines cardio pour utiliser le type d'exercice DUREE"""
    Machine = apps.get_model('machines', 'Machine')

    # Machines cardio qui doivent utiliser la durée
    cardio_machines = [
        "Vélo elliptique",
        "Tapis de course",
        "Rameur",
        "Vélo stationnaire",
        "Stepper"
    ]

    # Mettre à jour les machines cardio
    for machine in Machine.objects.filter(nom__in=cardio_machines):
        machine.type_exercice = 'DUREE'
        machine.save()


def reverse_update_cardio_machines(apps, schema_editor):
    """Remet les machines cardio en type REPETITIONS"""
    Machine = apps.get_model('machines', 'Machine')

    cardio_machines = [
        "Vélo elliptique",
        "Tapis de course",
        "Rameur",
        "Vélo stationnaire",
        "Stepper"
    ]

    for machine in Machine.objects.filter(nom__in=cardio_machines):
        machine.type_exercice = 'REPETITIONS'
        machine.save()


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_add_type_exercice'),
    ]

    operations = [
        migrations.RunPython(update_cardio_machines_to_duration, reverse_update_cardio_machines),
    ]
