# Generated by Django 4.2.7 on 2025-07-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_update_cardio_machines_to_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='tempo',
            field=models.CharField(blank=True, help_text='Tempo recommandé (ex: 3-1-2 pour 3s descente, 1s pause, 2s montée)', max_length=20, verbose_name='Tempo recommandé'),
        ),
    ]
