# Generated by Django 4.2.7 on 2025-01-27 10:30

from django.db import migrations

def update_cardio_machines_to_duration(apps, schema_editor):
    """
    Met à jour les machines cardio pour utiliser le type d'exercice DUREE
    """
    Machine = apps.get_model('machines', 'Machine')

    # Liste des machines cardio
    cardio_machines = [
        "Vélo elliptique",
        "Tapis de course",
        "Rameur",
        "Vélo stationnaire",
        "Stepper"
    ]

    # Mettre à jour les machines cardio
    for machine_name in cardio_machines:
        try:
            machine = Machine.objects.get(nom=machine_name)
            machine.type_exercice = 'DUREE'
            machine.save()
            print(f"Machine {machine_name} mise à jour vers type DUREE")
        except Machine.DoesNotExist:
            print(f"Machine {machine_name} non trouvée")

def reverse_update_cardio_machines(apps, schema_editor):
    """
    Remet les machines cardio en type REPETITIONS
    """
    Machine = apps.get_model('machines', 'Machine')

    cardio_machines = [
        "Vélo elliptique",
        "Tapis de course",
        "Rameur",
        "Vélo stationnaire",
        "Stepper"
    ]

    for machine_name in cardio_machines:
        try:
            machine = Machine.objects.get(nom=machine_name)
            machine.type_exercice = 'REPETITIONS'
            machine.save()
        except Machine.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_add_gif_field'),
    ]

    operations = [
        migrations.RunPython(update_cardio_machines_to_duration, reverse_update_cardio_machines),
    ]