# Generated by Django 4.2.7 on 2025-07-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_update_cardio_machines_to_duration'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL pour PostgreSQL - vérifie si la colonne existe avant de l'ajouter
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'machines_machine'
                    AND column_name = 'image_gif'
                ) THEN
                    ALTER TABLE machines_machine ADD COLUMN image_gif VARCHAR(500) NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE machines_machine DROP COLUMN IF EXISTS image_gif;
            """
        ),
    ]