# Generated by Django 4.2.7 on 2025-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_add_tempo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image_gif',
            field=models.URLField(blank=True, help_text="URL de l'animation GIF sur Cloudinary", max_length=500, null=True, verbose_name='Animation GIF (URL Cloudinary)'),
        ),
    ]
