# Generated by Django 4.2.7 on 2025-07-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_update_cardio_machines_to_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='instructions_utilisation',
            field=models.TextField(blank=True, help_text='Comment utiliser cette machine (pour import CSV)', verbose_name="Instructions d'utilisation (import)"),
        ),
    ]
