# Generated by Django 4.2.7 on 2025-07-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_add_instructions_utilisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='instructions_utilisation',
            field=models.TextField(blank=True, help_text='Comment utiliser cette machine (pour import CSV)', null=True, verbose_name="Instructions d'utilisation (import)"),
        ),
    ]
