# Generated by Django 4.2.7 on 2025-07-26 11:59

from django.db import migrations, connection


def check_and_fix_image_gif_column(apps, schema_editor):
    """
    Vérifie si la colonne image_gif existe déjà et corrige les problèmes de migration
    """
    with connection.cursor() as cursor:
        # Vérifier le type de base de données
        db_vendor = connection.vendor
        
        column_exists = False
        
        if db_vendor == 'postgresql':
            # PostgreSQL - utiliser information_schema
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='machines_machine' AND column_name='image_gif'
            """)
            column_exists = cursor.fetchone() is not None
            
        elif db_vendor == 'sqlite':
            # SQLite - utiliser PRAGMA table_info
            cursor.execute("PRAGMA table_info(machines_machine)")
            columns = [column[1] for column in cursor.fetchall()]
            column_exists = 'image_gif' in columns
        
        if column_exists:
            print("Colonne image_gif deja presente - migration ignoree")
        else:
            # Ajouter la colonne si elle n'existe pas
            try:
                cursor.execute("""
                    ALTER TABLE machines_machine 
                    ADD COLUMN image_gif varchar(500) NULL
                """)
                print("Colonne image_gif ajoutee")
            except Exception as e:
                if "already exists" in str(e).lower():
                    print("Colonne detectee par exception - ignoree")
                else:
                    raise e


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_add_image_gif_field'),
    ]

    operations = [
        migrations.RunPython(check_and_fix_image_gif_column, migrations.RunPython.noop),
    ]
