# Generated by Django 4.2.7 on 2025-08-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0013_machine_image_gif'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='machine',
            new_name='bf_machines_categor_5183f9_idx',
            old_name='machines_ma_categor_5cc98f_idx',
        ),
        migrations.RenameIndex(
            model_name='machine',
            new_name='bf_machines_popular_56f829_idx',
            old_name='machines_ma_popular_dda990_idx',
        ),
        migrations.AlterModelTable(
            name='categoriemachine',
            table='bf_categories_machines',
        ),
        migrations.AlterModelTable(
            name='groupemusculaire',
            table='bf_groupes_musculaires',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='bf_machines_equipements',
        ),
        migrations.AlterModelTable(
            name='machinecategorie',
            table='bf_machines_categories_liens',
        ),
        migrations.AlterModelTable(
            name='variantemachine',
            table='bf_variantes_exercices',
        ),
    ]
